# -*- coding: utf-8 -*-

# Map country name variants to the ones used in GeoNames.
country_names = {
    'Bolivia (Plurinational State of)': 'Bolivia',
    'Bosnia-Herzegovina': 'Bosnia and Herzegovina',
    'Brunei Darussalam': 'Brunei',
    'Burma': 'Myanmar',
    'Cape Verde Islands': 'Cape Verde',
    'Czech Republic': 'Czechia',
    'China, Hong Kong SAR': 'Hong Kong',
    'China, Macao SAR': 'Macao',
    'Congo': 'Republic of the Congo',
    'Congo, Republic of the': 'Republic of the Congo',
    'Congo, Democratic Republic of': 'Democratic Republic of the Congo',
    'Congo, Democratic Republic of the': 'Democratic Republic of the Congo',
    'Congo DR': 'Democratic Republic of the Congo',
    "Cote d'Ivoire": 'Ivory Coast',
    "Côte d'Ivoire": 'Ivory Coast',
    "Democratic People's Republic of Korea": 'North Korea',
    'England': 'United Kingdom',
    'Federated States of Micronesia': 'Micronesia',
    'FYR Macedonia': 'Macedonia',
    'Hong Kong, SAR China': 'Hong Kong',
    'Hong Kong, China': 'Hong Kong',
    'Iran (I.R.)': 'Iran',
    'Iran (Islamic Republic of)': 'Iran',
    'Iran, Islamic Republic of': 'Iran',
    'Korea (Rep.)': 'South Korea',
    'Korea Republic': 'South Korea',
    "Korea, Democratic People's Republic of": 'North Korea',
    'Korea, North': 'North Korea',
    'Korea, Republic of': 'South Korea',
    'Korea, South': 'South Korea',
    "Lao People's Democratic Republic": "Laos",
    'Libyan Arab Jamahiriya': 'Libya',
    'Macao, China': 'Macao',
    'Macau': 'Macao',
    'Macau, China': 'Macao',
    'Micronesia (Federated States of)': 'Micronesia',
    'Palestine': 'Palestinian Territory',
    'Palestinian Authority': 'Palestinian Territory',
    'Pitcairn Islands': 'Pitcairn',
    'Republic of Congo': 'Democratic Republic of the Congo',
    'Republic of Korea': 'South Korea',
    'Republic of Moldova': 'Moldova',
    'Réunion': 'Reunion',
    'Russian Federation': 'Russia',
    'Saint Barthélemy': 'Saint Barthelemy',
    'Saint Helena, Ascension and Tristan da Cunha': 'Saint Helena',
    'Slovak Republic': 'Slovakia',
    'State of Palestine': 'Palestinian Territory',
    'Syrian Arab Republic': 'Syria',
    'Taiwan Province of China': 'Taiwan',
    'Taiwan, China': 'Taiwan',
    'Tanzania, United Republic of': 'Tanzania',
    'TFYR Macedonia': 'Macedonia',
    'The Bahamas': 'Bahamas',
    'The former Yugoslav Republic of Macedonia': 'Macedonia',
    'the former Yugoslav Republic of Macedonia': 'Macedonia',
    'The Gambia': 'Gambia',
    'The Netherlands': 'Netherlands',
    'Timor-Leste': 'East Timor',
    'UAE': 'United Arab Emirates',
    'United Republic of Tanzania': 'Tanzania',
    'United Republic of Tanzania (the)': 'Tanzania',
    'United States Virgin Islands': 'U.S. Virgin Islands',
    'United States of America': 'United States',
    'US': 'United States',
    'USA': 'United States',
    'Vatican City': 'Vatican',
    'Venezuela (Bolivarian Republic of)': 'Venezuela',
    'Viet Nam': 'Vietnam',
    'West Bank and Gaza Strip': 'Palestinian Territory'
}