# -*- coding: utf-8 -*-

# Map country name variants to the ones used in GeoNames.
country_names = {
    'Bolivia (Plurinational State of)': 'Bolivia',
    'Bosnia-Herzegovina': 'Bosnia and Herzegovina',
    'Brunei Darussalam': 'Brunei',
    'Cape Verde Islands': 'Cape Verde',
    'China, Hong Kong SAR': 'Hong Kong',
    'China, Macao SAR': 'Macao',
    'Congo': 'Republic of the Congo',
    'Congo, Democratic Republic of': 'Democratic Republic of the Congo',
    'Congo DR': 'Democratic Republic of the Congo',
    "Côte d'Ivoire": 'Ivory Coast',
    "Democratic People's Republic of Korea": 'North Korea',
    'England': 'United Kingdom',
    'FYR Macedonia': 'Macedonia',
    'Hong Kong, SAR China': 'Hong Kong',
    'Hong Kong, China': 'Hong Kong',
    'Iran (I.R.)': 'Iran',
    'Iran (Islamic Republic of)': 'Iran',
    'Iran, Islamic Republic of': 'Iran',
    'Korea (Rep.)': 'South Korea',
    'Korea Republic': 'South Korea',
    "Korea, Democratic People's Republic of": 'North Korea',
    'Korea, Republic of': 'South Korea',
    "Lao People's Democratic Republic": "Laos",
    'Macao, China': 'Macao',
    'Macau, China': 'Macao',
    'Micronesia (Federated States of)': 'Micronesia',
    'Palestinian Authority': 'Palestinian Territory',
    'Republic of Congo': 'Democratic Republic of the Congo',
    'Republic of Korea': 'South Korea',
    'Republic of Moldova': 'Moldova',
    'Réunion': 'Reunion',
    'Russian Federation': 'Russia',
    'Slovak Republic': 'Slovakia',
    'State of Palestine': 'Palestinian Territory',
    'Syrian Arab Republic': 'Syria',
    'Taiwan Province of China': 'Taiwan',
    'Taiwan, China': 'Taiwan',
    'Tanzania, United Republic of': 'Tanzania',
    'TFYR Macedonia': 'Macedonia',
    'The former Yugoslav Republic of Macedonia': 'Macedonia',
    'the former Yugoslav Republic of Macedonia': 'Macedonia',
    'Timor-Leste': 'East Timor',
    'United Republic of Tanzania (the)': 'Tanzania',
    'United States Virgin Islands': 'U.S. Virgin Islands',
    'United States of America': 'United States',
    'Venezuela (Bolivarian Republic of)': 'Venezuela',
    'Viet Nam': 'Vietnam',
    'West Bank and Gaza Strip': 'Palestinian Territory'
}